### ISSUE TITLE
V5.0 Release Plan

### ISSUE THREAD

**Issue by maclover7** [thoughtbot/paperclip#2049]
There will be several breaking changes in Paperclip 5.0.0, so it's important that proper deprecation cycles are followed and good documentation is released to make the upgrade cycle as easy as possible.

**TODO:**
- [ ] Release a minor version FIRST (4.3.x) with the following changes:
  - [x] Deprecation warning if the user is still on aws-sdk v1, say v1 support will be dropped in v5.0.0
  - [x] Deprecation warning if the user is still on Rails 3.2.x, say 3.2.x support will be dropped in v5.0.0
- [x] Release a major version SECOND (5.0.0)
  - [x] Actual deprecation of aws-sdk v1 (this is a breaking change) (#2075)
  - [x] Actual deprecation of Rails 3.2 and 4.1 (this is a breaking change) (#2074)
  - [x] Remove locales from main repository (#1996)
  - [x] Add support for Rails 5.0.0 (#1976)
  - [x] Update documentation (#1976)

Deprecation notices should try and follow this style:
```ruby
require 'active_support/deprecation'
ActiveSupport::Deprecation.warn "deprecation notice goes here!"
```

As far as testing deprecation notices, here is a code example for that too:
```ruby
require 'active_support/testing/deprecation'

describe CoolClass do
  include ActiveSupport::Testing::Deprecation

  assert_deprecated do
    # code that will trigger deprecation goes here
  end
end
```

#1991 should be finished off whenever next 4.3.x release has been shipped.

ping @tute and @jyurek

**Comment by tute** [comment]
:+1: :clap: :heart:

**Comment by connorshea** [comment]
Now that Rails 5.0.0.beta1 is out, any updates on Paperclip 5.0.0?

**Comment by tute** [comment]
> Now that Rails 5.0.0.beta1 is out, any updates on Paperclip 5.0.0?

We are working on the checlist above. If there is no related issue, feel free to grab an item and move forward with it! I'd like to have a release in ~2 weeks or less.

**Comment by tute** [comment]
@maclover7 I forgot: Rails 5 has to work on the next 4.x release of paperclip too. Otherwise people have to upgrade in tandem both paperclip _and_ Rails. Will add it to the checklist.

**Comment by tute** [comment]
Notes from an email asking questions on how to implement deprecations:

> Where exactly you want the warning? I’ve not found a correct “method” to be the one that asserts we have a warning. Can you point me to a place in the code where deprecation should be thrown

I'd say when Paperclip loads. The `has_attachment` definition sounds good:

```ruby
# lib/paperclip.rb
def has_attached_file(name, options = {})
```

> I’ve tried to look for another example in the code, but I’ve not found one. So, can you help me with the Message you want to show there?

For Rails < 4.2:

> [paperclip] [deprecation] Rails 3.2 and 4.1 are unsupported as of Rails 5 release. Please upgrade to Rails 5 before upgrading paperclip.

For AWS 1:

> [paperclip] [deprecation] AWS v1 has been deprecated in paperclip 5. Please consider upgrading to AWS 2 before upgrading paperclip.

**Comment by connorshea** [comment]
Maybe specify that it's AWS SDK v1, not AWS v1? Other than that, looks good to me.

**Comment by kevcha** [comment]
Sorry for the spam, I referenced this issue in both commit and PR :/

**Comment by tute** [comment]
>  Add support for Rails 5.0.0 to version 4.x.

Do we need this?

**Comment by tute** [comment]
Removing that item, I don't think we do.

**Comment by tute** [comment]
This is ready now. Warning messages can be released again in the v4.3 branch, but I'll do when Rails 5 and paperclip v5 comes out in (non-beta).

Thank you all!

**Comment by connorshea** [comment]
:clap: thanks guys!

**Comment by plantoeat** [comment]
For what it is worth, I was confused by the deprecation warning below, after recently upgrading from paperclip 3.5.4 to 4.3.7.

`
[paperclip] [deprecation] Rails 3.2 and 4.1 are unsupported as of Rails 5 release. Please upgrade to Rails 5 before upgrading paperclip.
`

What about something like this?

`[paperclip] [deprecation] Rails 3.2 and 4.1 will be unsupported in Paperclip 5. Please upgrade to Rails 5 before upgrading Paperclip to release 5.`
